#!/bin/bash

if [[ -d dist ]]; then
    rm -fr dist
fi

# Personal website project
cd src/app
npm run build
mv dist ../..
cd ../..

# jekyll project
cd src/blog
bundle exec jekyll build
mv _site ../../dist/blog
cd ../..
