
name: Build and Deploy Website to GitHub Pages

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Builds src/homepage
  build_homepage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: src/homepage/package-lock.json

      - name: Install dependencies
        working-directory: src/homepage
        run: npm ci

      - name: Build Homepage
        working-directory: src/homepage
        run: npm run build

      - name: Add .nojekyll
        run: touch ./src/homepage/dist/.nojekyll

      - name: Upload Homepage Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: artifact
          path: ./src/homepage/dist 
          if-no-files-found: error
          retention-days: 1

  # Merges homepage artifact, blog
  # and all specified web applications
  link_apps:
    needs: build_homepage
    runs-on: ubuntu-latest

    steps:
      - name: Run ID Blog
        id: get-run-blog
        env:
          GH_TOKEN: ${{ secrets.GH_BLOG_LOAD_TOKEN }}
        run: |
          RUN_ID=$(gh run list \
            --repo ChuggleBug/Blog \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId')
          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"

      - name: Run ID Wikigraph
        id: get-run-wikigraph
        env:
          GH_TOKEN: ${{ secrets.GH_APP_LOAD_TOKEN }}
        run: |
          RUN_ID=$(gh run list \
            --repo ChuggleBug/Wikigraph \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId')
          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"

      - name: Load Homepage
        uses: actions/download-artifact@v8.0.1
        with: 
          name: artifact
          path: ./dist

      - name: Load Blog
        uses: actions/download-artifact@v8.0.1
        with: 
          repository: ChuggleBug/Blog
          name: dist
          path: ./dist/blog
          run-id: ${{ steps.get-run-blog.outputs.run_id }}
          github-token: ${{ secrets.GH_BLOG_LOAD_TOKEN }}

      - name: Load WikiGraph
        uses: actions/download-artifact@v8.0.1
        with: 
          repository: ChuggleBug/WikiGraph
          name: dist
          path: ./dist/app/wikigraph
          run-id: ${{ steps.get-run-wikigraph.outputs.run_id }}
          github-token: ${{ secrets.GH_APP_LOAD_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  # Deploy Site
  deploy:
    needs: link_apps
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
